workflows:
  android-kotlin-workflow:
    name: Android Kotlin Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      - name: Build Android APK
        script: |
          # Gradlew ෆයිල් එක තියෙන තැන සොයාගෙන ඒ ෆෝල්ඩරය ඇතුළට යෑම
          GRADLEW_DIR=$(find . -name "gradlew" -exec dirname {} \; | head -n 1)
          if [ -n "$GRADLEW_DIR" ]; then
            cd "$GRADLEW_DIR"
            echo "Working directory changed to: $(pwd)"
          else
            echo "Error: gradlew file not found anywhere!" && exit 1
          fi
          
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - "**/build/outputs/apk/release/*.apk"
